DROP TABLE Address CASCADE CONSTRAINTS PURGE;

DROP TABLE Hospital CASCADE CONSTRAINTS PURGE;

DROP TABLE Building CASCADE CONSTRAINTS PURGE;

DROP TABLE Floor CASCADE CONSTRAINTS PURGE;

DROP TABLE Room CASCADE CONSTRAINTS PURGE;

DROP TABLE GeoLocation CASCADE CONSTRAINTS PURGE;

DROP TABLE HealthInsurance CASCADE CONSTRAINTS PURGE;

DROP TABLE Person CASCADE CONSTRAINTS PURGE;

DROP TABLE PersonHealthInsurance CASCADE CONSTRAINTS PURGE;

DROP TABLE HospitalEmployee CASCADE CONSTRAINTS PURGE;

DROP TABLE Patient CASCADE CONSTRAINTS PURGE;

DROP TABLE AuthorizationRole CASCADE CONSTRAINTS PURGE;

DROP TABLE RoleAssignment CASCADE CONSTRAINTS PURGE;

DROP TABLE TreatmentType CASCADE CONSTRAINTS PURGE;

DROP TABLE Authorization CASCADE CONSTRAINTS PURGE;

DROP TABLE TreatmentSchedule CASCADE CONSTRAINTS PURGE;

DROP TABLE BillOfMaterial CASCADE CONSTRAINTS PURGE;

DROP TABLE Material CASCADE CONSTRAINTS PURGE;

DROP TABLE RoomEquipment CASCADE CONSTRAINTS PURGE;

DROP TABLE Treatment CASCADE CONSTRAINTS PURGE;

DROP TABLE Stay CASCADE CONSTRAINTS PURGE;

DROP TABLE Disease CASCADE CONSTRAINTS PURGE;

DROP TABLE Diagnostics CASCADE CONSTRAINTS PURGE;

DROP TABLE MedicalRecord CASCADE CONSTRAINTS PURGE;